---
deployment:
  tasks:
    - export COMPOSER_HOME="${HOME}/.composer"
    - /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction 2>&1
    - rsync -a --delete --exclude='.git' --exclude='uploads' "$(pwd)/" "${HOME}/sistemadombag.com/" 2>&1
