<?php
// ── 2026-04-01 · Schema completo — todas as tabelas em maiúsculo ──────────────

executarsql('SET FOREIGN_KEY_CHECKS = 0');

// 1. GRUPO_USUARIO
executarsql("
    CREATE TABLE IF NOT EXISTS `GRUPO_USUARIO` (
      `GRU_CODIGO`    INT UNSIGNED  NOT NULL AUTO_INCREMENT,
      `GRU_NOME`      VARCHAR(50)   NOT NULL,
      `GRU_DESCRICAO` VARCHAR(200)  NULL,
      PRIMARY KEY (`GRU_CODIGO`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

// 2. USUARIOS
executarsql("
    CREATE TABLE IF NOT EXISTS `USUARIOS` (
      `USU_CODIGO` INT UNSIGNED  NOT NULL AUTO_INCREMENT,
      `USU_LOGIN`  VARCHAR(25)   NOT NULL,
      `USU_SENHA`  VARCHAR(255)  NOT NULL,
      `USU_NOME`   VARCHAR(50)   NOT NULL,
      `USU_PERFIL` VARCHAR(20)   NOT NULL DEFAULT 'usuario',
      `USU_ATIVO`  TINYINT(1)    NOT NULL DEFAULT 1,
      `GRU_CODIGO` INT UNSIGNED  NULL,
      PRIMARY KEY (`USU_CODIGO`),
      UNIQUE KEY `UQ_USU_LOGIN` (`USU_LOGIN`),
      KEY `FK_USU_GRUPO` (`GRU_CODIGO`),
      CONSTRAINT `FK_USU_GRUPO`
        FOREIGN KEY (`GRU_CODIGO`) REFERENCES `GRUPO_USUARIO` (`GRU_CODIGO`)
        ON DELETE SET NULL ON UPDATE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

// 3. PERMISSAO_ACESSO
executarsql("
    CREATE TABLE IF NOT EXISTS `PERMISSAO_ACESSO` (
      `PAC_CODIGO`     INT UNSIGNED NOT NULL AUTO_INCREMENT,
      `PAC_GRU_CODIGO` INT UNSIGNED NOT NULL,
      `PAC_PAGINA`     VARCHAR(150) NOT NULL,
      PRIMARY KEY (`PAC_CODIGO`),
      UNIQUE KEY `UK_GRU_PAG` (`PAC_GRU_CODIGO`, `PAC_PAGINA`),
      CONSTRAINT `FK_PAC_GRUPO`
        FOREIGN KEY (`PAC_GRU_CODIGO`) REFERENCES `GRUPO_USUARIO` (`GRU_CODIGO`)
        ON DELETE CASCADE ON UPDATE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

// 4. DEPARTAMENTOS
executarsql("
    CREATE TABLE IF NOT EXISTS `DEPARTAMENTOS` (
      `DP_CODIGO`    INT UNSIGNED NOT NULL AUTO_INCREMENT,
      `DP_DESCRICAO` VARCHAR(25)  NOT NULL,
      PRIMARY KEY (`DP_CODIGO`),
      UNIQUE KEY `UQ_DP_DESCRICAO` (`DP_DESCRICAO`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

executarsql("
    INSERT IGNORE INTO `DEPARTAMENTOS` (`DP_DESCRICAO`) VALUES
      ('Impressão'), ('Corte e Solda'), ('Costura'), ('Acabamento'), ('Expedição')
");

// 5. MAQUINAS
executarsql("
    CREATE TABLE IF NOT EXISTS `MAQUINAS` (
      `MAQ_CODIGO`          INT UNSIGNED  NOT NULL AUTO_INCREMENT,
      `MAQ_DESCRICAO`       VARCHAR(120)  NOT NULL,
      `MAQ_QTDE`            DECIMAL(6,2)  NOT NULL DEFAULT 1.00,
      `MAQ_PRODUCAO_MIN`    DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
      `MAQ_HORAS_DIA`       DECIMAL(5,2)  NOT NULL DEFAULT 8.00,
      `DP_CODIGO`           INT UNSIGNED  NOT NULL,
      `MAQ_GRUPO`           VARCHAR(80)   NULL DEFAULT NULL,
      `MAQ_CONTA_PRODUCAO`  TINYINT(1)    NOT NULL DEFAULT 1,
      PRIMARY KEY (`MAQ_CODIGO`),
      UNIQUE KEY `UQ_MAQ_DESCRICAO` (`MAQ_DESCRICAO`),
      KEY `FK_MAQ_DEPTO` (`DP_CODIGO`),
      CONSTRAINT `FK_MAQ_DEPTO`
        FOREIGN KEY (`DP_CODIGO`) REFERENCES `DEPARTAMENTOS` (`DP_CODIGO`)
        ON DELETE RESTRICT ON UPDATE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

// 6. PRODUTOS
executarsql("
    CREATE TABLE IF NOT EXISTS `PRODUTOS` (
      `PRO_CODIGO`        INT UNSIGNED NOT NULL AUTO_INCREMENT,
      `PRO_CODIGO_YZ`     VARCHAR(30)  NOT NULL,
      `PRO_DESCRICAO`     VARCHAR(200) NOT NULL DEFAULT '',
      `PRO_TIPO`          ENUM('BAG','SACARIA','') NOT NULL DEFAULT '',
      `PRO_TRAVADO`       TINYINT(1)   NOT NULL DEFAULT 0,
      `PRO_IMPRESSAO`     TINYINT(1)   NOT NULL DEFAULT 0,
      `PRO_VALVULADO`     TINYINT(1)   NOT NULL DEFAULT 0,
      `PRO_COMPRIMENTO`   INT          NULL DEFAULT NULL,
      `PRO_MAQ_IMPRESSAO` VARCHAR(50)  NULL DEFAULT NULL,
      `PRO_FLUXO`         VARCHAR(300) NOT NULL DEFAULT '',
      `PRO_CATEGORIA`     VARCHAR(60) GENERATED ALWAYS AS (
        CASE
          WHEN PRO_TIPO = 'BAG'     AND PRO_TRAVADO = 0 AND PRO_IMPRESSAO = 0 THEN 'Bag sem impressão'
          WHEN PRO_TIPO = 'BAG'     AND PRO_TRAVADO = 0 AND PRO_IMPRESSAO = 1 THEN 'Bag com impressão'
          WHEN PRO_TIPO = 'BAG'     AND PRO_TRAVADO = 1 AND PRO_IMPRESSAO = 0 THEN 'Bag travado sem impressão'
          WHEN PRO_TIPO = 'BAG'     AND PRO_TRAVADO = 1 AND PRO_IMPRESSAO = 1 THEN 'Bag travado com impressão'
          WHEN PRO_TIPO = 'SACARIA' AND PRO_IMPRESSAO = 0                     THEN 'Sacaria sem impressão'
          WHEN PRO_TIPO = 'SACARIA' AND PRO_IMPRESSAO = 1                     THEN 'Sacaria com impressão'
          ELSE 'Não classificado'
        END
      ) STORED,
      `PRO_CRIADO`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (`PRO_CODIGO`),
      UNIQUE KEY `UQ_PRO_CODIGO_YZ` (`PRO_CODIGO_YZ`),
      KEY `IDX_PRO_CATEGORIA` (`PRO_CATEGORIA`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

// 7. CLIENTES
executarsql("
    CREATE TABLE IF NOT EXISTS `CLIENTES` (
      `CLI_CODIGO`    INT UNSIGNED NOT NULL AUTO_INCREMENT,
      `CLI_CODIGO_YZ` VARCHAR(30)  NULL DEFAULT NULL,
      `CLI_NOME`      VARCHAR(160) NOT NULL DEFAULT '',
      `CLI_FANTASIA`  VARCHAR(160) NOT NULL DEFAULT '',
      `CLI_CNPJ`      VARCHAR(20)  NULL DEFAULT NULL,
      `CLI_UF`        CHAR(2)      NOT NULL DEFAULT '',
      `CLI_CIDADE`    VARCHAR(60)  NOT NULL DEFAULT '',
      `CLI_FONE`      VARCHAR(30)  NOT NULL DEFAULT '',
      `CLI_EMAIL`     VARCHAR(120) NOT NULL DEFAULT '',
      `CLI_CRIADO`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (`CLI_CODIGO`),
      UNIQUE KEY `UQ_CLI_CODIGO_YZ` (`CLI_CODIGO_YZ`),
      UNIQUE KEY `UQ_CLI_CNPJ` (`CLI_CNPJ`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

// 8. VENDAS
executarsql("
    CREATE TABLE IF NOT EXISTS `VENDAS` (
      `VEN_CODIGO`         INT UNSIGNED  NOT NULL AUTO_INCREMENT,
      `VEN_CODIGO_YZIDRO`  VARCHAR(30)   NOT NULL,
      `CLI_CODIGO`         INT UNSIGNED  NULL DEFAULT NULL,
      `VEN_REPRESENTANTE`  VARCHAR(100)  NOT NULL DEFAULT '',
      `VEN_EMISSAO`        DATE          NULL DEFAULT NULL,
      `VEN_ENTREGA`        DATE          NULL DEFAULT NULL,
      `VEN_TOTAL`          DECIMAL(14,2) NOT NULL DEFAULT 0.00,
      `VEN_SEGMENTO`       VARCHAR(64)   NOT NULL DEFAULT '',
      `VEN_GRUPO_CLIENTES` VARCHAR(64)   NOT NULL DEFAULT '',
      `VEN_OBS`            TEXT          NULL,
      `VEN_STATUS`         VARCHAR(50)   NULL DEFAULT NULL,
      `VEN_IMPORTADO_EM`   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (`VEN_CODIGO`),
      UNIQUE KEY `UQ_VEN_CODIGO_YZIDRO` (`VEN_CODIGO_YZIDRO`),
      KEY `IDX_VEN_ENTREGA` (`VEN_ENTREGA`),
      KEY `FK_VEN_CLIENTE` (`CLI_CODIGO`),
      CONSTRAINT `FK_VEN_CLIENTE`
        FOREIGN KEY (`CLI_CODIGO`) REFERENCES `CLIENTES` (`CLI_CODIGO`)
        ON DELETE SET NULL ON UPDATE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

// 9. ITENS_VENDAS
executarsql("
    CREATE TABLE IF NOT EXISTS `ITENS_VENDAS` (
      `IV_CODIGO`        INT UNSIGNED  NOT NULL AUTO_INCREMENT,
      `VEN_CODIGO`       INT UNSIGNED  NOT NULL,
      `PRO_CODIGO`       INT UNSIGNED  NOT NULL,
      `IV_QTDE`          DECIMAL(12,3) NOT NULL DEFAULT 0.000,
      `IV_VLR_UNIT`      DECIMAL(12,4) NOT NULL DEFAULT 0.0000,
      `IV_TOTAL`         DECIMAL(14,2) NOT NULL DEFAULT 0.00,
      `IV_UNIDADE`       VARCHAR(10)   NOT NULL DEFAULT '',
      `IV_STATUS`        ENUM(
                           'Pendente de produção',
                           'Produção',
                           'Aguardando',
                           'Aguardando envio',
                           'Aguardando expedição',
                           'Finalizado'
                         ) NOT NULL DEFAULT 'Pendente de produção',
      `IV_PRIORIDADE`    INT           NOT NULL DEFAULT 0,
      `IV_OBS`           TEXT          NULL,
      `IV_ATUALIZADO_EM` DATETIME      NULL DEFAULT NULL,
      PRIMARY KEY (`IV_CODIGO`),
      UNIQUE KEY `UQ_IV_VENDA_PROD` (`VEN_CODIGO`, `PRO_CODIGO`),
      KEY `IDX_IV_STATUS`     (`IV_STATUS`),
      KEY `IDX_IV_PRIORIDADE` (`IV_PRIORIDADE`),
      KEY `FK_IV_PRODUTO`     (`PRO_CODIGO`),
      CONSTRAINT `FK_IV_VENDA`
        FOREIGN KEY (`VEN_CODIGO`) REFERENCES `VENDAS` (`VEN_CODIGO`)
        ON DELETE CASCADE ON UPDATE CASCADE,
      CONSTRAINT `FK_IV_PRODUTO`
        FOREIGN KEY (`PRO_CODIGO`) REFERENCES `PRODUTOS` (`PRO_CODIGO`)
        ON DELETE RESTRICT ON UPDATE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

// 10. ITENS_VENDAS_IMAGENS
executarsql("
    CREATE TABLE IF NOT EXISTS `ITENS_VENDAS_IMAGENS` (
      `IMG_CODIGO`    INT          NOT NULL AUTO_INCREMENT,
      `IV_CODIGO`     INT          NOT NULL,
      `IMG_ARQUIVO`   VARCHAR(255) NOT NULL,
      `IMG_NOME_ORIG` VARCHAR(255) NOT NULL,
      `IMG_CRIADO_EM` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (`IMG_CODIGO`),
      KEY `IDX_IMG_IV` (`IV_CODIGO`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

// 11. PRODUCAO_DIARIA
executarsql("
    CREATE TABLE IF NOT EXISTS `PRODUCAO_DIARIA` (
      `PD_CODIGO`      INT UNSIGNED  NOT NULL AUTO_INCREMENT,
      `PD_DATA`        DATE          NOT NULL,
      `MAQ_CODIGO`     INT UNSIGNED  NOT NULL,
      `PD_FUNCIONARIO` VARCHAR(120)  NOT NULL DEFAULT '',
      `PD_HORARIO_INI` TIME          NOT NULL,
      `PD_HORARIO_FIM` TIME          NOT NULL,
      `PD_QUANTIDADE`  DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      `PD_PEDIDO`      VARCHAR(30)   NOT NULL DEFAULT '',
      `PD_COMENTARIO`  TEXT          NULL,
      `PD_CRIADO_EM`   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (`PD_CODIGO`),
      KEY `IDX_PD_DATA`     (`PD_DATA`),
      KEY `IDX_PD_MAQUINA`  (`MAQ_CODIGO`),
      KEY `IDX_PD_DATA_MAQ` (`PD_DATA`, `MAQ_CODIGO`),
      CONSTRAINT `FK_PD_MAQUINA`
        FOREIGN KEY (`MAQ_CODIGO`) REFERENCES `MAQUINAS` (`MAQ_CODIGO`)
        ON DELETE RESTRICT ON UPDATE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

// 14. PARAMETROS
executarsql("
    CREATE TABLE IF NOT EXISTS `PARAMETROS` (
      `PAR_CHAVE` VARCHAR(100) NOT NULL,
      `PAR_VALOR` TEXT         NULL,
      PRIMARY KEY (`PAR_CHAVE`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

// Usuário administrador padrão — login: 1 / senha: 1
executarsql("
    INSERT IGNORE INTO `USUARIOS` (`USU_LOGIN`, `USU_SENHA`, `USU_NOME`, `USU_PERFIL`) VALUES
      ('1', '\$2y\$10\$h5DXS9uJqrZalmwSf09Egu.m23CSYoIUUFEsEv3T8k4pwUlZNtTwK', 'Administrador', 'admin')
");

executarsql('SET FOREIGN_KEY_CHECKS = 1');
