<?php
// ── 2026-08-21 · Cadastro de Células de Produção ──────────────────────────────
executarsql("
    CREATE TABLE IF NOT EXISTS `CELULA_PRODUCAO` (
      `CEL_CODIGO` INT UNSIGNED NOT NULL AUTO_INCREMENT,
      `CEL_NOME`   VARCHAR(100) NOT NULL,
      PRIMARY KEY (`CEL_CODIGO`),
      UNIQUE KEY `UQ_CEL_NOME` (`CEL_NOME`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");

executarsql("
    CREATE TABLE IF NOT EXISTS `CELULA_FUNCIONARIO` (
      `CEL_CODIGO` INT UNSIGNED NOT NULL,
      `FU_CODIGO`  INT NOT NULL,
      PRIMARY KEY (`CEL_CODIGO`, `FU_CODIGO`),
      CONSTRAINT `FK_CELFUNC_CELULA` FOREIGN KEY (`CEL_CODIGO`)
        REFERENCES `CELULA_PRODUCAO` (`CEL_CODIGO`) ON DELETE CASCADE ON UPDATE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
");
