CREATE TABLE IF NOT EXISTS leads_ads (
    id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    lead_id             VARCHAR(120)   NULL,
    data_criacao        DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nome                VARCHAR(160)   NULL,
    telefone            VARCHAR(60)    NULL,
    email               VARCHAR(180)   NULL,
    empresa             VARCHAR(180)   NULL,
    produto_interesse   VARCHAR(180)   NULL,
    origem_botao        VARCHAR(120)   NULL,
    origem_lp           VARCHAR(120)   NULL,
    gclid               VARCHAR(255)   NULL,
    gbraid              VARCHAR(255)   NULL,
    wbraid              VARCHAR(255)   NULL,
    utm_source          VARCHAR(120)   NULL,
    utm_medium          VARCHAR(120)   NULL,
    utm_campaign        VARCHAR(180)   NULL,
    status_atual        VARCHAR(40)    NOT NULL DEFAULT 'NOVO',
    data_qualificacao   DATETIME       NULL,
    data_venda_fechada  DATETIME       NULL,
    data_perda          DATETIME       NULL,
    motivo_perda        TEXT           NULL,
    valor_venda         DECIMAL(15,2)  NULL,
    vendedor            VARCHAR(120)   NULL,
    referer_url         VARCHAR(255)   NULL,
    landing_url         VARCHAR(255)   NULL,
    ip_origem           VARCHAR(64)    NULL,
    user_agent          VARCHAR(255)   NULL,
    payload_json        LONGTEXT       NULL,
    dedupe_hash         CHAR(64)       NULL,
    criado_em           DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em       DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_leads_status   (status_atual),
    INDEX idx_leads_data     (data_criacao),
    INDEX idx_leads_email    (email),
    INDEX idx_leads_tel      (telefone),
    INDEX idx_leads_lp       (origem_lp),
    INDEX idx_leads_vendedor (vendedor),
    UNIQUE KEY uq_leads_dedupe (dedupe_hash),
    UNIQUE KEY uq_leads_lead_id (lead_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
