<?php
declare(strict_types=1);
require_once $_SERVER['DOCUMENT_ROOT'] . '/config/config.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/modules/login/auth.php';
require_once $_SERVER['DOCUMENT_ROOT'] . '/modules/crm/leads_common.php';

$pdo = leadsPdo();
leadsEnsureSchema($pdo);
$proto = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$landing = $proto . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost') . ($_SERVER['REQUEST_URI'] ?? '');
$token = '1Il66UA1xXyoD1bWE1B-s7fekK2ZpEUpVjlxw8Hhm1E4';
?>
<!DOCTYPE html><html lang="pt-br"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Teste de Lead | DOMBAG</title><link rel="stylesheet" href="/public/css/unified_admin.css"><style>.field-row{display:grid;grid-template-columns:1fr 1fr;gap:12px;}@media(max-width:700px){.field-row{grid-template-columns:1fr;}}.response-box{display:none;padding:14px 16px;border-radius:var(--radius);font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11.5px;line-height:1.65;white-space:pre-wrap;word-break:break-word;border:1px solid var(--border);background:rgba(0,0,0,.15);color:var(--text-muted);margin-top:14px;max-height:240px;overflow-y:auto;}.response-box.ok{border-color:rgba(0,201,167,.3);color:var(--teal);} .response-box.err{border-color:rgba(239,68,68,.3);color:var(--red);}</style></head><body><div class="app-wrapper"><?php include $_SERVER['DOCUMENT_ROOT'] . '/shared/sidebar.php'; ?><div class="main"><header class="topbar"><div class="topbar-left"><div class="page-title"><h1>Teste de Lead</h1><p>Envia para o site o mesmo payload que antes ia para a planilha.</p></div></div></header><div class="content"><div class="form-panel"><div class="form-panel-head"><h2>Payload da LP</h2><span class="count-badge">Apps Script → Site</span></div><form id="leadForm"><div class="form-body">
<div class="field-row"><div class="field"><label>lead_id</label><input type="text" name="lead_id" value="teste-<?= date('YmdHis') ?>"></div><div class="field"><label>data_criacao</label><input type="text" name="data_criacao" value="<?= leadsH(date('c')) ?>"></div></div>
<div class="field-row"><div class="field"><label>Nome *</label><input type="text" name="nome" required></div><div class="field"><label>Telefone</label><input type="text" name="telefone"></div></div>
<div class="field-row"><div class="field"><label>E-mail</label><input type="email" name="email"></div><div class="field"><label>Empresa</label><input type="text" name="empresa"></div></div>
<div class="field-row"><div class="field"><label>Produto interesse</label><select name="produto_interesse"><option value="">Selecione</option><option>Big Bag</option><option>Sacaria</option><option>Ambos</option></select></div><div class="field"><label>Vendedor</label><input type="text" name="vendedor" value="VENDEDOR TESTE"></div></div>
<div class="field-row"><div class="field"><label>origem_botao</label><input type="text" name="origem_botao" value="teste_manual"></div><div class="field"><label>origem_LP</label><input type="text" name="origem_LP" value="BB_V1"></div></div>
<div class="field-row"><div class="field"><label>gclid</label><input type="text" name="gclid" value="<?= leadsH((string) ($_GET['gclid'] ?? 'gclid_teste')) ?>"></div><div class="field"><label>gbraid</label><input type="text" name="gbraid" value="<?= leadsH((string) ($_GET['gbraid'] ?? '')) ?>"></div></div>
<div class="field-row"><div class="field"><label>wbraid</label><input type="text" name="wbraid" value="<?= leadsH((string) ($_GET['wbraid'] ?? '')) ?>"></div><div class="field"><label>utm_source</label><input type="text" name="utm_source" value="<?= leadsH((string) ($_GET['utm_source'] ?? 'google')) ?>"></div></div>
<div class="field-row"><div class="field"><label>utm_medium</label><input type="text" name="utm_medium" value="<?= leadsH((string) ($_GET['utm_medium'] ?? 'cpc')) ?>"></div><div class="field"><label>utm_campaign</label><input type="text" name="utm_campaign" value="<?= leadsH((string) ($_GET['utm_campaign'] ?? 'campanha_teste')) ?>"></div></div>
<div class="field-row"><div class="field"><label>status_atual</label><select name="status_atual"><?php foreach (LEADS_STATUS_OPTIONS as $k => $l): ?><option value="<?= leadsH($k) ?>" <?= $k === 'NOVO' ? 'selected' : '' ?>><?= leadsH($l) ?></option><?php endforeach; ?></select></div><div class="field"><label>valor_venda</label><input type="text" name="valor_venda"></div></div>
<div class="field"><label>motivo_perda / observação</label><textarea name="motivo_perda"></textarea></div>
<input type="hidden" name="landing_url" value="<?= leadsH($landing) ?>">
</div><div class="form-actions"><button type="submit" class="btn-primary" id="btnEnviar"><span id="btnTxt">Enviar payload</span></button></div></form><div class="response-box" id="responseBox"></div></div></div></div></div>
<script>
const form=document.getElementById('leadForm'),box=document.getElementById('responseBox'),btn=document.getElementById('btnEnviar'),btnTxt=document.getElementById('btnTxt');form.addEventListener('submit',async function(e){e.preventDefault();btn.disabled=true;btnTxt.textContent='Enviando…';box.style.display='none';box.className='response-box';const fd=new FormData(form);const payload=Object.fromEntries(fd.entries());try{const res=await fetch('/modules/crm/webhook_leads.php',{method:'POST',headers:{'Content-Type':'application/json','X-Webhook-Token':'<?= $token ?>'},body:JSON.stringify(payload)});const data=await res.json();box.classList.add(data.ok?'ok':'err');box.textContent=JSON.stringify(data,null,2);box.style.display='block';}catch(err){box.classList.add('err');box.textContent='Erro ao enviar lead.\n\n'+err;box.style.display='block';}btn.disabled=false;btnTxt.textContent='Enviar payload';});
</script>
</body></html>
